name: customerregistrationsystem
services:
  prometheus:
    image: prom/prometheus:v3.3.1
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 127.0.0.1:9090:9090
    network_mode: 'host'
  grafana:
    image: grafana/grafana:12.0.0
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 127.0.0.1:3000:3000
    network_mode: 'host'
