name: customerregistrationsystem
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
  mailhog:
    extends:
      file: ./mailhog.yml
      service: mailhog
