name: customerregistrationsystem
services:
  sonar:
    container_name: sonarqube
    image: sonarqube:25.5.0.107428-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - 127.0.0.1:9001:9000
      - 127.0.0.1:9000:9000
